name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Build the Docker image
        run: make test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Gogitver release
        id: gogitver_release
        uses: syncromatics/gogitver-release@0.0.9
        with:
          gogitver-version: "0.8.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ship the Docker image
        run: make ship
        env:
          VERSION: ${{ steps.gogitver_release.outputs.release_tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
